n=int(input("Number of persons in a single room: "))
print("Rent Calculator Among the Roomates")
rent=int(input("Enter total Rent: "))
food=int(input("Enter total food Ordered for Snacking: "))
bill=int(input("Enter Electrcity units spend: "))
unit=int(input("Enter Charge Per Unit: "))
print("Total Amount to be paid: ",rent+food+bill*unit)
Amount=int(((rent+food+bill*unit)/n))
print("Total amount to be paid by each person: ", Amount)